FROM node:20-alpine AS build

ARG VITE_AUTH_SERVICE_URL=http://localhost:8081
ARG VITE_EMPLOYEE_SERVICE_URL=http://localhost:8082
ARG VITE_CATALOG_SERVICE_URL=http://localhost:8083
ARG VITE_INVENTORY_SERVICE_URL=http://localhost:8084
ARG VITE_PROCUREMENT_SERVICE_URL=http://localhost:8085
ARG VITE_SALES_SERVICE_URL=http://localhost:8086
ARG VITE_PRODUCTION_SERVICE_URL=http://localhost:8087
ARG VITE_QUALITY_SERVICE_URL=http://localhost:8088
ARG VITE_WAREHOUSE_SERVICE_URL=http://localhost:8089
ARG VITE_FINANCE_SERVICE_URL=http://localhost:8090

ENV VITE_AUTH_SERVICE_URL=$VITE_AUTH_SERVICE_URL
ENV VITE_EMPLOYEE_SERVICE_URL=$VITE_EMPLOYEE_SERVICE_URL
ENV VITE_CATALOG_SERVICE_URL=$VITE_CATALOG_SERVICE_URL
ENV VITE_INVENTORY_SERVICE_URL=$VITE_INVENTORY_SERVICE_URL
ENV VITE_PROCUREMENT_SERVICE_URL=$VITE_PROCUREMENT_SERVICE_URL
ENV VITE_SALES_SERVICE_URL=$VITE_SALES_SERVICE_URL
ENV VITE_PRODUCTION_SERVICE_URL=$VITE_PRODUCTION_SERVICE_URL
ENV VITE_QUALITY_SERVICE_URL=$VITE_QUALITY_SERVICE_URL
ENV VITE_WAREHOUSE_SERVICE_URL=$VITE_WAREHOUSE_SERVICE_URL
ENV VITE_FINANCE_SERVICE_URL=$VITE_FINANCE_SERVICE_URL

WORKDIR /app
COPY frontend/package.json ./package.json

RUN npm install
COPY frontend/ .
RUN npm run build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
